backend_repo_workdir: '/home/ubuntu/yaptide'
backend_repo_version: master

backend_password: "password"

backend_cluster: ""
backend_cert_auth_url: ""
backend_backend_external_url: "http://localhost:5000"
backend_keycloak_base_url: ""
backend_keycloak_realm: ""

backend_ssl_crt : "server.crt"
backend_ssl_key : "server.key"

ansible_become: false
